name: rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pdfplumber==0.10.3
    - spacy==3.7.2
    - https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.7.0/xx_ent_wiki_sm-3.7.0.tar.gz
    - numpy==1.24.3
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - sentence-transformers==2.2.2
    - transformers==4.30.2
    - huggingface-hub==0.16.4
    - faiss-cpu==1.7.4
    - mistral-inference
    - mistral-common
    - PyPDF2
